### ISSUE TITLE
[enhancement] Provide release and binary for mac and linux

### ISSUE THREAD

**Issue by at15** [dyweb/dy-weekly-generator#12]
Currently we need to build the generator locally, however it would be better to provide binary release. It's essential for the incoming [dy-bot](https://github.com/dyweb/dy-bot), the bot can download the generator if it didn't find one in path

**Comment by gaocegege** [comment]
I think we could release v0.2.1 and add the binary releases.

**Comment by at15** [comment]
@codeworm96 maybe we can add a `Makefile` for `make build`, `make package`, etc. 
Or we can just use cargo ... I don't remember if you can define commands in `Cargo.toml`, also oh-my-zsh has auto complete for makefile.

An example for my thesis project ... https://github.com/benchhub/benchhub/blob/master/Makefile

**Comment by codeworm96** [comment]
Do you mean `cargo install --path .`?

**Comment by at15** [comment]
@codeworm96 kind of, but I want the binary be packed as tarball and put in github's release, and rust can cross compile right?

**Comment by at15** [comment]
@codeworm96 any update on this? 或者我可以开始我的第三次 rust 入门(到放弃 ....

**Comment by codeworm96** [comment]
FYI https://rust-lang-nursery.github.io/cli-wg/tutorial/packaging.html#distributing-binaries

**Comment by codeworm96** [comment]
> Unless you use crates that explicitly need external libraries to be installed on the target system (like using the system’s version of OpenSSL)

We need OpenSSL... Maybe we can have a try...
