### ISSUE TITLE
[enhancement] Add section

### ISSUE THREAD

**Issue by gaocegege** [dyweb/dy-weekly-generator#4]
/assign @gaocegege

**Comment by at15** [comment]
不要骗自己了 ... /w

**Comment by codeworm96** [comment]
According to discussion at #3, it's better to separate comments into sections.

**Comment by gaocegege** [comment]
我不是骗自己，我是在骗 codeworm96

**Comment by gaocegege** [comment]
I will add a 

***
between the comments.
