### ISSUE TITLE
[feature] Support link

### ISSUE THREAD

**Issue by gaocegege** [dyweb/dy-weekly-generator#8]
Similar to #7 , we do not support link now.

Ref https://dongyueweb.com/weekly/weekly/2018/04/23/weekly.html

**Comment by codeworm96** [comment]
Maybe we should consider using a github favored markdown render to get these support for free.

**Comment by gaocegege** [comment]
Yeah, it is a good idea, I will take a look.

**Comment by gaocegege** [comment]
Close in https://github.com/dyweb/weekly/pull/36
